apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: openfga-security-validator
  labels:
    app.kubernetes.io/name: openfga-operator
    app.kubernetes.io/component: admission-controller
spec:
  clientConfig:
    service:
      name: openfga-operator-webhook
      namespace: openfga-system
      path: /validate
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["authorization.openfga.dev"]
    apiVersions: ["v1alpha1"]
    resources: ["openfgas"]
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/part-of: openfga-operator
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/part-of: openfga-operator
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  timeoutSeconds: 10
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: openfga-policy-validator
  labels:
    app.kubernetes.io/name: openfga-operator
    app.kubernetes.io/component: admission-controller
spec:
  clientConfig:
    service:
      name: openfga-operator-webhook
      namespace: openfga-system
      path: /validate-policy
  rules:
  - operations: ["CREATE", "UPDATE", "DELETE"]
    apiGroups: ["networking.k8s.io"]
    apiVersions: ["v1"]
    resources: ["networkpolicies"]
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/part-of: openfga-operator
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["secrets"]
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/part-of: openfga-operator
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  timeoutSeconds: 10