apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga-operator
  namespace: openfga-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: RUST_LOG
          value: "debug"
        - name: ENABLE_PLAYGROUND
          value: "true"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi