apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
  annotations:
    dsv.delinea.com/inject: "true"
    dsv.delinea.com/path: "/databases/openfga-mysql"
    dsv.delinea.com/secrets: "username,password,root-password"
type: Opaque
stringData:
  # These will be populated by DSV injector
  username: "placeholder"
  password: "placeholder"
  root-password: "placeholder"
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-secret-test
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database-test
  annotations:
    dsv.delinea.com/inject: "true"
    dsv.delinea.com/secrets: |
      - path: "/databases/openfga-mysql"
        secrets:
          - key: "username"
            env: "MYSQL_USER"
          - key: "password"
            env: "MYSQL_PASSWORD"
          - key: "root-password"
            env: "MYSQL_ROOT_PASSWORD"
        volumeMount:
          name: "mysql-secrets"
          mountPath: "/etc/mysql-secrets"
          readOnly: true
spec:
  restartPolicy: Never
  containers:
  - name: test-container
    image: mysql:8.0
    command: ["/bin/sh"]
    args: ["-c", "echo 'Testing secret injection'; sleep 30"]
    env:
    - name: MYSQL_DATABASE
      value: "openfga"
    volumeMounts:
    - name: mysql-secrets
      mountPath: /etc/mysql-secrets
      readOnly: true
  volumes:
  - name: mysql-secrets
    secret:
      secretName: mysql-credentials
      defaultMode: 0400
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-secret-rotation
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: secret-rotation
spec:
  schedule: "0 2 * * 1"  # Weekly on Mondays at 2 AM
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            dsv.delinea.com/inject: "true"
            dsv.delinea.com/secrets: |
              - path: "/databases/openfga-mysql"
                secrets:
                  - key: "username"
                    env: "MYSQL_USER"
                  - key: "password"
                    env: "MYSQL_PASSWORD"
                  - key: "root-password"
                    env: "MYSQL_ROOT_PASSWORD"
                  - key: "new-password"
                    env: "NEW_MYSQL_PASSWORD"
        spec:
          restartPolicy: OnFailure
          containers:
          - name: rotate-secrets
            image: mysql:8.0
            command: ["/bin/sh"]
            args:
            - -c
            - |
              echo "Rotating MySQL password..."
              mysql -h mysql-openfga -u root -p$MYSQL_ROOT_PASSWORD -e "ALTER USER '$MYSQL_USER'@'%' IDENTIFIED BY '$NEW_MYSQL_PASSWORD';"
              echo "Password rotation completed"
            env:
            - name: MYSQL_DATABASE
              value: "openfga"