apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
  annotations:
    dsv.delinea.com/inject: "true"
    dsv.delinea.com/path: "/databases/openfga-postgres"
    dsv.delinea.com/secrets: "username,password"
type: Opaque
stringData:
  # These will be populated by DSV injector
  username: "placeholder"
  password: "placeholder"
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-secret-test
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database-test
  annotations:
    dsv.delinea.com/inject: "true"
    dsv.delinea.com/secrets: |
      - path: "/databases/openfga-postgres"
        secrets:
          - key: "username"
            env: "POSTGRES_USER"
          - key: "password"
            env: "POSTGRES_PASSWORD"
        volumeMount:
          name: "postgres-secrets"
          mountPath: "/etc/postgres-secrets"
          readOnly: true
spec:
  restartPolicy: Never
  containers:
  - name: test-container
    image: postgres:15-alpine
    command: ["/bin/sh"]
    args: ["-c", "echo 'Testing secret injection'; sleep 30"]
    env:
    - name: POSTGRES_DB
      value: "openfga"
    volumeMounts:
    - name: postgres-secrets
      mountPath: /etc/postgres-secrets
      readOnly: true
  volumes:
  - name: postgres-secrets
    secret:
      secretName: postgres-credentials
      defaultMode: 0400
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-secret-rotation
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: secret-rotation
spec:
  schedule: "0 2 * * 1"  # Weekly on Mondays at 2 AM
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            dsv.delinea.com/inject: "true"
            dsv.delinea.com/secrets: |
              - path: "/databases/openfga-postgres"
                secrets:
                  - key: "username"
                    env: "POSTGRES_USER"
                  - key: "password"
                    env: "POSTGRES_PASSWORD"
                  - key: "new-password"
                    env: "NEW_POSTGRES_PASSWORD"
        spec:
          restartPolicy: OnFailure
          containers:
          - name: rotate-secrets
            image: postgres:15-alpine
            command: ["/bin/sh"]
            args:
            - -c
            - |
              echo "Rotating PostgreSQL password..."
              PGPASSWORD=$POSTGRES_PASSWORD psql -h postgresql-openfga -U $POSTGRES_USER -d openfga -c "ALTER USER $POSTGRES_USER PASSWORD '$NEW_POSTGRES_PASSWORD';"
              echo "Password rotation completed"
            env:
            - name: POSTGRES_DB
              value: "openfga"