apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-management-policies
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: dsv-injector
    app.kubernetes.io/component: secrets-management
data:
  security-policy.yaml: |
    apiVersion: security.delinea.com/v1
    kind: SecretPolicy
    metadata:
      name: openfga-secret-policy
      namespace: openfga-system
    spec:
      secretRotation:
        enabled: true
        schedule: "0 2 * * 1"  # Weekly rotation on Mondays at 2 AM
        maxAge: "168h"  # 7 days
        notificationEmail: "security@company.com"
      accessControl:
        allowedServiceAccounts:
        - dsv-injector
        - openfga-operator
        - keycloak
        - postgresql-openfga
        - mysql-openfga
        deniedServiceAccounts: []
        allowedNamespaces:
        - openfga-system
        - openfga-workloads
      auditPolicy:
        enabled: true
        logLevel: "INFO"
        destinations:
        - type: "webhook"
          url: "https://security-audit.company.com/api/v1/secrets"
        - type: "file"
          path: "/var/log/dsv-audit.log"
      encryptionPolicy:
        transitEncryption: true
        atRestEncryption: true
        keyRotationInterval: "30d"
  secret-injection-policy.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: secret-injection-policy
    data:
      policy: |
        # Default injection behavior
        defaultBehavior: "inject"
        
        # Secret mount patterns
        secretMounts:
          - name: "database-secrets"
            mountPath: "/etc/database-secrets"
            volumeType: "secret"
            readOnly: true
            defaultMode: 0400
          - name: "application-secrets"
            mountPath: "/etc/app-secrets"
            volumeType: "secret"
            readOnly: true
            defaultMode: 0400
        
        # Environment variable injection
        envVarInjection:
          enabled: true
          prefix: "DSV_"
          excludePatterns:
          - ".*_PASSWORD$"  # Don't inject passwords as env vars
          - ".*_SECRET$"    # Don't inject secrets as env vars
        
        # Init container configuration
        initContainer:
          image: "delinea/dsv-init:1.0.4"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
  backup-encryption-policy.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: backup-encryption-policy
    data:
      policy: |
        # Backup encryption configuration
        backupEncryption:
          enabled: true
          algorithm: "AES-256-GCM"
          keyDerivation: "PBKDF2"
          saltLength: 32
          iterations: 100000
        
        # Key management
        keyManagement:
          provider: "dsv"
          keyPath: "/encryption/backup-keys"
          rotationPolicy:
            enabled: true
            schedule: "0 1 1 * *"  # Monthly on 1st at 1 AM
            retainPreviousKeys: 3
        
        # Compression settings
        compression:
          enabled: true
          algorithm: "gzip"
          level: 6