apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: openfga-operator-prod

resources:
  - ../../base

namePrefix: prod-

labels:
  - pairs:
      environment: production
      deployment.type: production

patches:
  - path: patches/operator-prod.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: openfga-operator
  - path: patches/keycloak-prod.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: keycloak
  - path: patches/storage-prod.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: keycloak-data

configMapGenerator:
  - name: environment-config
    literals:
      - environment=production
      - log-level=info
      - enable-playground=false
      - enable-audit-logging=true

secretGenerator:
  - name: prod-secrets
    literals:
      - admin-password=CHANGE_IN_PRODUCTION
      - db-password=CHANGE_IN_PRODUCTION  
      - jwt-secret=CHANGE_IN_PRODUCTION

images:
  - name: openfga/openfga
    newTag: v1.5.0
  - name: openfga-operator
    newTag: v1.0.0

replicas:
  - name: openfga-operator
    count: 3
  - name: keycloak
    count: 3