apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-ui
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/component: network-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble-ui
      app.kubernetes.io/component: network-observability
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hubble-ui
        app.kubernetes.io/component: network-observability
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      serviceAccountName: hubble-ui
      containers:
      - name: frontend
        image: quay.io/cilium/hubble-ui:v0.13.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        env:
        - name: EVENTS_SERVER_PORT
          value: "8090"
        - name: FLOWS_API_ADDR
          value: "hubble-relay:80"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      - name: backend
        image: quay.io/cilium/hubble-ui-backend:v0.13.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        ports:
        - name: grpc
          containerPort: 8090
          protocol: TCP
        env:
        - name: EVENTS_SERVER_PORT
          value: "8090"
        - name: FLOWS_API_ADDR
          value: "hubble-relay:80"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hubble-ui
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/component: network-observability
spec:
  selector:
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/component: network-observability
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-ui
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/component: network-observability
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubble-ui
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: hubble-ui
    app.kubernetes.io/component: network-observability
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hubble.example.com
    secretName: hubble-ui-tls
  rules:
  - host: hubble.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hubble-ui
            port:
              number: 80