apiVersion: v1
kind: ConfigMap
metadata:
  name: openfga-operator-config
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: openfga-operator
    app.kubernetes.io/component: operator
data:
  config.yaml: |
    operator:
      logLevel: info
      metricsAddr: "0.0.0.0:8080"
      webhookAddr: "0.0.0.0:9443"
      leaderElection: true
      watchNamespace: ""
    security:
      enableAdmissionController: true
      requireImageSigning: true
      allowedRepositories:
        - "openfga/openfga"
        - "ghcr.io/openfga/openfga"
      securityPolicies:
        requireNonRoot: true
        requireReadOnlyRootFilesystem: true
        disallowPrivilegeEscalation: true
    features:
      networkPolicies: true
      monitoring: true
      tracing: true
    defaults:
      image: "openfga/openfga:v1.5.0"
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi