apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfga-operator
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: openfga-operator
    app.kubernetes.io/component: operator
automountServiceAccountToken: true