apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: openfga-system
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: portworx-sc-db
  resources:
    requests:
      storage: 100Gi