apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: portworx-sc-db
  resources:
    requests:
      storage: 10Gi