apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
type: Opaque
stringData:
  username: admin
  password: CHANGE_ME_IN_PRODUCTION
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
type: Opaque
stringData:
  username: keycloak
  password: CHANGE_ME_IN_PRODUCTION