apiVersion: v1
kind: Namespace
metadata:
  name: openfga-system
  labels:
    name: openfga-system
    app.kubernetes.io/name: openfga-system
    app.kubernetes.io/part-of: openfga-operator
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfga-workloads
  labels:
    name: openfga-workloads
    app.kubernetes.io/name: openfga-workloads
    app.kubernetes.io/part-of: openfga-operator
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted